# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          Brian Choi
url:              blog.brianchoi.net
paginate:         1
baseurl:          /
author:
  name:           Brian Choi
  url:            https://twitter.com/bchoi12
  email:          brian@brianchoi.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
pages_list:
  Archives:	  '/archives'
