# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Brian Choi
tagline:          The Blog
url:              
paginate:         3
baseurl:          
author:
  name:           Brian Choi
  url:            https://twitter.com/bchoi12
  email:          brian@brianchoi.net

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
pages_list:
  Archives:	  '/archives'
  Why:	  	  '/about'
